apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml
- workflow-role-binding.yaml
- workflow-role.yaml

patchesStrategicMerge:
- argo-server-service.yaml
- workflow-controller-cm.yaml
- argo-binding.yaml
- argo-server-binding.yaml
